# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BookManager' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BookManager

  target 'BookManagerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BookManagerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
